import navProfilePic from "./assets/navProfilePic.jpg";
export const logs = [
  {
    user: navProfilePic,
    id: "ct0091",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0092",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0093",
    action: "UNPUBLISH",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0094",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0095",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0096",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0097",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0098",
    action: "CREATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0099",
    action: "UPDATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0082",
    action: "UNPUBLISH",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0083",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0084",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0080",
    action: "UNPUBLISH",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0081",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0087",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0029",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0029",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0039",
    action: "CREATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0028",
    action: "UPDATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00920",
    action: "UNPUBLISH",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00392",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00192",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00924",
    action: "UNPUBLISH",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00292",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00692",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct04092",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00292",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00921",
    action: "CREATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct01092",
    action: "UPDATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00c92",
    action: "UNPUBLISH",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00xa92",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct009a2",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct009s2",
    action: "UNPUBLISH",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00a92",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct009y2",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00rd92",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct003f92",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00dx92",
    action: "CREATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct009wc2",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00vu92",
    action: "CREATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0ts092",
    action: "UPDATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00ub92",
    action: "UNPUBLISH",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00wc92",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00wx92",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00sbh92",
    action: "UNPUBLISH",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00z92",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00xm92",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct009ka2",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0is092",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00ie92",
    action: "CREATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct0ow092",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00ms92",
    action: "CREATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00ow92",
    action: "UPDATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00ps92",
    action: "UNPUBLISH",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct00wo92",
    action: "UPDATE",
    type: "Content",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
  {
    user: navProfilePic,
    id: "ct009o22",
    action: "CREATE",
    type: "Model",
    environment: "Master",
    timestamp: "26 Nov 2022",
  },
];
